### ISSUE TITLE
Voice-text channel support

### ISSUE THREAD

**Issue by Khitiara** [Khitiara/TtsBot#1]
Waiting on https://github.com/DSharpPlus/DSharpPlus/pull/1149 for now, RFC on whether to always use associated channel or continue to support the existing method as an option

**Comment by OoLunar** [comment]
Hello! I saw that you mentioned our PR here, so I thought I'd let you know that the PR has been merged and is available on the latest nightly found over at https://www.nuget.org/packages/DSharpPlus/4.3.0-nightly-01140

**Comment by Khitiara** [comment]
thanks, im in the middle of implementing my usage of it now!
